# Generated by Django 5.0.3 on 2024-04-23 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pensamento_critico_criatividade', models.FloatField(verbose_name='Pensamento Crítico e Criatividade')),
                ('comunicacao', models.FloatField(verbose_name='Comunicação')),
                ('colaboracao', models.FloatField(verbose_name='Colaboração')),
                ('qualidade_entregas', models.FloatField(verbose_name='Qualidade das Entregas')),
                ('presenca', models.FloatField(verbose_name='Presença')),
                ('entrega_prazos', models.FloatField(verbose_name='Entrega e Prazos')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('alunos', models.ManyToManyField(related_name='grupos', to='feedbackApp.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
